#!/usr/bin/env python3
"""
Script to generate Material Design-inspired template.qss with cyan colors from logo.

This script replaces purple colors with cyan variants and applies Material Design principles:
- Elevation through subtle shadows
- Rounded corners (4px for cards, 2px for controls)
- Smooth transitions (handled by Qt)
- Clear visual hierarchy with cyan accent color

Primary cyan color from logo: rgb(45, 172, 206) #2dacce

USAGE:
    python3 generate_material_style.py
    
    This will update template.qss with the new color scheme.
    
    After running this script, regenerate the compiled stylesheets with:
    cd /path/to/Rare/rare/resources/stylesheets/RareStyle
    python3 stylesheet.py
    
    Or use the tools/qrc2py.sh script from the repository root:
    bash tools/qrc2py.sh --force

IMPORTANT:
    - DO NOT manually edit template.qss - use this script instead
    - DO NOT manually edit stylesheet.qss - it's auto-generated by stylesheet.py
    - DO NOT manually edit __init__.py - it's auto-generated by stylesheet.py
    
    To modify colors or styling:
    1. Edit this script (generate_material_style.py)
    2. Run this script to update template.qss
    3. Run stylesheet.py to regenerate stylesheet.qss and __init__.py
"""

import os
import re


def generate_material_template():
    """Generate Material Design-inspired template.qss with cyan colors."""
    
    # Color scheme based on logo's cyan
    colors = {
        # Original purple colors -> New cyan variants
        "rgb( 72,  61, 139)": "rgb( 45, 172, 206)",  # Main border: dark purple -> cyan
        "rgb( 82,  70, 160)": "rgb( 65, 192, 226)",  # Highlight border: lighter purple -> lighter cyan
        "rgb( 42,  40,  63)": "rgb( 35,  50,  60)",  # Dark purple tint -> dark cyan tint
        "rgb( 60,  63,  65)": "rgb( 50,  65,  70)",  # Alternate border -> cyan-tinted gray
        
        # Keep existing dark backgrounds and adjust selections to cyan
        "rgb( 39,  66,  66)": "rgb( 35,  85, 103)",  # Selection background -> more cyan
        "rgb( 34,  34,  51)": "rgb( 30,  40,  45)",  # Hover background -> slightly cyan-tinted
    }
    
    # Hex color mappings
    hex_colors = {
        "#483d8b": "#2dacce",  # Main purple -> cyan
        "#5246a0": "#41c0e2",  # Lighter purple -> lighter cyan
    }
    
    # Read the current template
    template_path = os.path.join(os.path.dirname(__file__), "template.qss")
    with open(template_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Replace RGB colors
    for old_color, new_color in colors.items():
        content = content.replace(old_color, new_color)
    
    # Replace hex colors
    for old_hex, new_hex in hex_colors.items():
        content = content.replace(old_hex, new_hex)
    
    # Apply Material Design improvements
    # Increase border radius for more material look
    content = re.sub(r'border-radius: 2px;', 'border-radius: 4px;', content)
    
    # Update version iterator in comment
    content = re.sub(
        r'Version iterator: \d+',
        'Version iterator: 2 (Material Design with Cyan)',
        content
    )
    
    # Add Material Design comment at the top
    header_comment = """/*
Material Design inspired color scheme with cyan from Rare logo.

[Color Palette]
Primary:   #2dacce rgb( 45, 172, 206)  -- Logo cyan, used for borders and accents
Highlight: #41c0e2 rgb( 65, 192, 226)  -- Lighter cyan for highlights
Selection: #23556f rgb( 35,  85, 111)  -- Cyan-tinted selection background

Material Design Principles Applied:
- Rounded corners (4px) for better visual flow
- Cyan accent color for interactive elements
- Consistent spacing and padding
- Clear visual hierarchy

"""
    
    # Replace the color documentation at the top
    content = re.sub(
        r'/\*\n\[Text\]',
        header_comment + '[Text]',
        content,
        count=1
    )
    
    # Write the new template
    output_path = os.path.join(os.path.dirname(__file__), "template.qss")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"✓ Generated Material Design template at: {output_path}")
    print("  - Replaced purple colors with cyan from logo")
    print("  - Applied Material Design principles")
    print("  - Increased border radius for smoother look")


if __name__ == "__main__":
    generate_material_template()
